title: SonsuzUs Programlama
description: Programlama ve Yazılım
url: "https://program.sonsuz.us"
theme: bulma-clean-theme

# Tema Özel Ayarları
show_sidebar: true     # Sağdaki gereksiz yan menüyü kapatır
menubar_dark: true       # Üst menüyü koyu (senin mavinin kontrastına uygun) yapar
show_footer: true        # C.S. Rhymes yazan alt kısmı kontrol etmemizi sağlar

# Yazar Bilgileri (Yazıların altında görünür)
author: Sonsuz Us

custom_css: 
  - /assets/css/custom.css